### ISSUE TITLE
Stocks not refreshing

### ISSUE THREAD

**Issue by sastools** [sthocs/firestocks#2]
It appears the IEX api is not providing pricing anymore
and all the stock prices are not being displayed.
Has something changed on their end?

**Comment by sthocs** [comment]
Yeah, IEX stopped their free-tier plan :(
I need to check if their PAYGO plan could be reasonably cheap, otherwise I'm open to suggestions of free APIs.

**Comment by sthocs** [comment]
I've switched to [Financial Modeling Prep](https://site.financialmodelingprep.com/) in e1fa006, as they provide a nice and simple API with a free tier. Unfortunately the free plan is too limited to serve all users with my API Key, so I've added an option for people to add their API Key in the options page. Still open to APIs suggestions!

**Comment by sastools** [comment]
Working well. Thanks for the update.
